print("Welcome to Credit Card Application Simulator!")
print("this is accurate to real life (NO HE'S LYING)")
age = int(input("enter age here "))
print(age)
q1 = input("ok so now i have to ask you what is the square root of 64 ")
q2 = input("if you wrote a book about the main character slowly going insane, what would the last line be? ")
if age = 0: input("YOU WERE JUST BORN")
elif age < 18: input("NOPE")
elif age =<18: print(q1)
if q1 == 8: print(q2)
elif q1 == 55: input("WRONG! DUMMY")
elif q1 == "gg": input("THERMONUCLEAR GET THE RPG")

if q2 == "ooo im insane i went insane aaa": input("weljflakjdlkfjalksdflkajeklfjalkejdf credit card is yours")
elif q2 == "i dont know": input("dang thats crazy")
elif q2 == "gg": print("BYE")
